### ISSUE TITLE
Unauthenticated GitHub API activity gets rate-limited

### ISSUE THREAD

**Issue by nex3** [frenck/action-setup-yq#35]
This action makes a request to https://api.github.com/repos/mikefarah/yq/releases/latest without any authentication, which leads to frequent rate-limiting and broken actions as a result. It should be possible and encouraged to pass in an [authentication token](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) to avoid these rate limits.

**Comment by stovmascript** [comment]
I think you could introduce a "token" input in your composite action so that users use their token to make the request.
